# Generated by Django 5.0.2 on 2024-05-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmsession',
            name='is_system_message',
            field=models.BooleanField(default=False),
        ),
    ]
