# Generated by Django 5.0.2 on 2024-05-16 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_dmsession_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(128)]),
        ),
    ]
