# kind/prometheus-value.yml
serverFiles:
  prometheus.yml:
    # global:
    #   scrape_interval: 15s 
    scrape_configs:
      - job_name: 'nginx'
        static_configs:
          # - targets: ['http://host.docker.internal:9113']
          - targets: ['host.docker.internal:9113']
      - job_name: 'django'
        metrics_path: '/metrics'
        scheme: 'https'
        static_configs:
          - targets: ['host.docker.internal:443']
        tls_config:
          insecure_skip_verify: true
      - job_name: 'frontend'
        metrics_path: '/metrics'
        scheme: 'http'
        static_configs:
          - targets: ['localhost:3000']
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['192.168.10.140:9100']
      # cAdvisorの設定をここに挿入
      - job_name: 'cadvisor'
        static_configs:
          - targets: ['host.docker.internal:8080']
      - job_name: 'elasticsearch-exporter'
        static_configs:
          - targets: ['elasticsearch-exporter:9114']

