# FROM node:20-alpine

# # Ganache CLIをインストール
# RUN npm install -g ganache-cli

# # Ganache CLIを実行するデフォルトコマンド
# ENTRYPOINT ["ganache-cli"]
# # デフォルトのポート8545でGanacheを実行
# CMD ["--host", "0.0.0.0"]

FROM trufflesuite/ganache-cli:latest
