# Generated by Django 5.0.2 on 2024-03-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_ponggameresult_delete_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponggameresult',
            name='match_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
