# Generated by Django 5.0.2 on 2024-04-08 14:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_ponggameresult_match_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponggameresult',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
