# Generated by Django 5.0.2 on 2024-05-16 13:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0005_tournament_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ponggameresult',
            name='name_loser',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ponggameresult',
            name='name_winner',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='player_nicknames',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, size=None),
        ),
    ]
