# Generated by Django 5.0.2 on 2024-06-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0006_alter_match_player1_alter_match_player2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='last_finished_round',
            field=models.IntegerField(default=0),
        ),
    ]
