# Generated by Django 5.0.2 on 2024-06-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0008_alter_tournament_last_finished_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_playing',
            field=models.BooleanField(default=False),
        ),
    ]
