# 参考:【Grafana のプロビジョニング | Grafana のドキュメント】 <https://grafana.com/docs/grafana/latest/administration/provisioning/#data-sources>
# 参考:【Prometheus data source | Grafana documentation】 <https://grafana.com/docs/grafana/latest/datasources/prometheus/>

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # <int> Sets the organization id. Defaults to orgId 1.
    orgId: 1
    # <string> Sets a custom UID to reference this data source in other parts of the configuration.
    # If not specified, Grafana generates one.
    uid: ft_trans_prometheus
    # <string> Sets the data source's URL, including the port.
    url: http://prometheus:9090
    # <bool> Toggles whether the data source is pre-selected
    # for new panels. You can set only one default
    # data source per organization.
    isDefault: true
    # <int> Sets the version. Used to compare versions when updating. Ignored when creating a new data source.
    version: 1
    # <bool> Allows users to edit data sources from the Grafana UI.
    editable: true
    # jsonData:
    #   httpMethod: POST
    #   manageAlerts: true
    #   prometheusType: Prometheus
    #   prometheusVersion: 2.44.0
    #   cacheLevel: 'High'
    #   disableRecordingRules: false
    #   incrementalQueryOverlapWindow: 10m
    #   exemplarTraceIdDestinations:
    #     # Field with internal link pointing to data source in Grafana.
    #     # datasourceUid value can be anything, but it should be unique across all defined data source uids.
    #     - datasourceUid: my_jaeger_uid
    #       name: traceID

    #     # Field with external link.
    #     - name: traceID
    #       url: 'http://localhost:3000/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Jaeger%22,%7B%22query%22:%22$${__value.raw}%22%7D%5D'