# Generated by Django 5.0.2 on 2024-05-02 03:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_has_2fa_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blocking_users',
            field=models.ManyToManyField(related_name='blocking_me', to=settings.AUTH_USER_MODEL),
        ),
    ]
