# Generated by Django 5.0.2 on 2024-05-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_blocking_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='is_system'),
        ),
    ]
