# Generated by Django 5.0.2 on 2024-05-08 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_friend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='friend',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='user',
            new_name='sender',
        ),
    ]
