version: "3.7"

services:
  ft_django:
    container_name: ft_django
    build: ./ft_django
    image: ft_django
    env_file:
      - .env
    volumes:
      - ${VOLUME_PATH}/ft_django/code:/code
      - ${VOLUME_PATH}/ft_django/static:/static/
      - ${VOLUME_PATH}/ft_django/uwsgi:/etc/uwsgi
      - ${VOLUME_PATH}:/container_output
    networks:
      - db_transcendence
      - http_transcendence
    ports:
      - "${DJANGO_PORT}:8080"
    depends_on:
      - postgres
    # restart: unless-stopped
    init: true

  postgres:
    container_name: postgres
    build: ./postgres
    image: postgres
    env_file:
      - .env
    environment:
      # 冗長だが明示的に指定。　.envを上書きしたい場合変更する
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
      - POSTGRES_LOCAL_AUTH_METHOD=${POSTGRES_LOCAL_AUTH_METHOD}
    volumes:
      - ${VOLUME_PATH}/postgres:/var/lib/postgresql/data
      - ${VOLUME_PATH}:/container_output
    networks:
      - db_transcendence
    ports:
      - "${POSTGRES_PORT}:5432" 
    restart: unless-stopped
    init: true
