version: "3.7"

volumes:
  postgres_vol:
    driver_opts:
      type: none
      device: ${VOLUME_PATH}/postgres
      o: bind
  django_vol:
    driver_opts:
      type: none
      device: ${VOLUME_PATH}/django
      o: bind

services:
  nginx:
    container_name: nginx
    build: ./nginx
    image: nginx
    env_file:
      - .env
    ports:
      - ${NGINX_SSL_PORT}:443
    volumes:
      # - ${VOLUME_PATH}/wordpress:/var/www/html
      - ${SSL_CERT_PATH}:/etc/nginx/ssl/nginx.crt
      - ${SSL_KEY_PATH}:/etc/nginx/ssl/nginx.key
    networks:
      - http_transcendence
    restart: unless-stopped
    init: true

  postgres:
    container_name: postgres
    build: ./postgres
    image: postgres
    env_file:
      - .env
    environment:
      # 冗長だが明示的に指定。　.envを上書きしたい場合変更する
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
      - POSTGRES_LOCAL_AUTH_METHOD=${POSTGRES_LOCAL_AUTH_METHOD}
    volumes:
      - ${VOLUME_PATH}/postgres:/var/lib/postgresql/data
      - ${VOLUME_PATH}:/container_output
    networks:
      - db_transcendence
    ports:
      - ${POSTGRES_PORT}:5432 
    restart: unless-stopped
    init: true

  django:
    container_name: django
    build: ./django
    image: django
    env_file:
      - .env
    volumes:
      - ${VOLUME_PATH)/django:/code
    networks:
      - db_transcendence
      - http_transcendence
    ports:
      - ${DJANGO_PORT}:8000
    depends_on:
      - postgres
    restart: unless-stopped
    intit: true

networks:
  http_transcendence:
    driver: bridge
    name: http_transcendence
  db_transcendence:
    driver: bridge
    name: db_transcendence