version: "3.7"
# docker/srcs/docker-compose-prometheus.yml
services:
  prometheus:
    container_name: prometheus
    build: ./prometheus
    image: prometheus
    env_file:
      - .env
    ports:
      - "9090:9090"
    networks:
      - web_transcendence
      - db_transcendence
      - elastic_transcendence
    volumes:
      - ${VOLUME_PATH}/prometheus:/prometheus

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    # restart: unless-stopped
    ports:
     - '3009:3000'
    volumes:
      - ${VOLUME_PATH}/grafana:/var/lib/grafana
    env_file:
      - .env
    environment:
     - GF_SERVER_ROOT_URL=http://my.grafana.server/
     - GF_INSTALL_PLUGINS=grafana-clock-panel
     - GF_LOG_LEVEL=debug
    networks:
      - web_transcendence