version: "3.7"

networks:
  http_transcendence:
    driver: bridge
    name: http_transcendence
  db_transcendence:
    driver: bridge
    name: db_transcendence

volumes:
  postgres_vol:
    driver_opts:
      type: none
      device: ${VOLUME_PATH}/postgres
      o: bind
  wp_vol:
    driver_opts:
      type: none
      device: ${VOLUME_PATH}/wordpress
      o: bind
  maria_vol:
    driver_opts:
      type: none
      device: ${VOLUME_PATH}/mariadb
      o: bind

services:
  nginx:
    container_name: nginx
    build: ./nginx
    image: nginx
    env_file:
      - .env
    ports:
      - ${NGINX_SSL_PORT}:443
    volumes:
      - ${VOLUME_PATH}/wordpress:/var/www/html
      - ${SSL_CERT_PATH}:/etc/nginx/ssl/nginx.crt
      - ${SSL_KEY_PATH}:/etc/nginx/ssl/nginx.key
    networks:
      - http_transcendence
    depends_on:
      - wordpress
    restart: unless-stopped
    init: true

  postgres:
    container_name: postgres
    build: ./postgres
    image: postgres
    env_file:
      - .env
    environment:
      # 冗長だが明示的に指定。　.envを上書きしたい場合変更する
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
    volumes:
      - ${VOLUME_PATH}/postgres:/var/lib/postgresql/data
      - ${VOLUME_PATH}:/container_output
    networks:
      - db_transcendence
    ports:
      - ${POSTGRES_PORT}:5432 
    restart: unless-stopped
    init: true

  mariadb:
    container_name: mariadb
    build: ./mariadb
    image: mariadb
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - ${VOLUME_PATH}/mariadb:/var/lib/mysql
      - ${VOLUME_PATH}:/container_output
    networks:
      - db_transcendence
    ports:
      - ${MARIADB_PORT}:3306
    restart: unless-stopped
    init: true

  wordpress:
    container_name: wordpress
    build:  ./wordpress
    image: wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - ${VOLUME_PATH}/wordpress:/var/www/html
      - ${VOLUME_PATH}:/container_output
    networks:
      - http_transcendence
      - db_transcendence
    restart: unless-stopped
    init: true
