version: "3.7"
# docker/srcs/docker-compose.yml
# ----------------------------------------------------------
# 他のdocker-compose-*.ymlの場所は下記
# 
# docker-compose-yml/
# ├── docker-compose-blockchain.yml
# ├── docker-compose-elk.yml
# ├── docker-compose-exporter.yml
# ├── docker-compose-monitor.yml
# ├── docker-compose-networks.yml
# └── docker-compose-web.yml
# 
# ----------------------------------------------------------

volumes:
  ft_transcendence_vol:
    driver: local
    driver_opts:
      type: 'bind'
      device: '${VOLUME_PATH}/ft_transcendence'
  log_vol:
    driver: local
    driver_opts:
      type: 'bind'
      device: '${VOLUME_PATH}/log_vol'
  log_django_vol:
    driver: local
    driver_opts:
      type: 'bind'
      device: '${VOLUME_PATH}/log_django_vol'


# 参考:【Compose ファイル version 3 リファレンス — Docker-docs-ja 24.0 ドキュメント】 https://docs.docker.jp/compose/compose-file/compose-file-v3.html#compose-file-v3-volume-configuration-reference