version: "3.7"
# docker/srcs/docker-compose.yml

# ----------------------------------------------------------
# 他のdocker-compose-*.ymlは ./docker-compose-yml/
# ----------------------------------------------------------

volumes:
  ft_transcendence_vol:
    driver: local
    driver_opts:
      type: 'bind'
      device: '${VOLUME_PATH}/ft_transcendence'

# 参考:【Compose ファイル version 3 リファレンス — Docker-docs-ja 24.0 ドキュメント】 https://docs.docker.jp/compose/compose-file/compose-file-v3.html#compose-file-v3-volume-configuration-reference