version: "3.7"

volumes:
  postgres_vol:
    driver_opts:
      type: none
      device: ${VOLUME_PATH}/postgres
      o: bind
  pgadmin_vol:
    driver_opts:
      type: none
      device: ${VOLUME_PATH}/pgadmin
      o: bind
  django_vol:
    driver_opts:
      type: none
      device: ${VOLUME_PATH}/django
      o: bind

networks:
  web_transcendence:
    driver: bridge
    name: web_transcendence
  db_transcendence:
    driver: bridge
    name: db_transcendence

services:
  nginx:
    container_name: nginx
    build: ./nginx
    image: nginx
    env_file:
      - .env
    ports:
      - "${NGINX_SSL_PORT}:443"
    environment:
      - SERVER_NAME=${SERVER_NAME}
    volumes:
      - ${VOLUME_PATH}/nginx/static:/static
      - ${SSL_CERT_PATH}:/etc/nginx/ssl/nginx.crt
      - ${SSL_KEY_PATH}:/etc/nginx/ssl/nginx.key
      - ${VOLUME_PATH}:/container_output
    networks:
      - web_transcendence
    restart: unless-stopped
    depends_on:
      - pgadmin
      - ft_django
    init: true

