# Generated by Django 5.0.2 on 2024-03-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='votes2',
            field=models.IntegerField(default=0),
        ),
    ]
