apiVersion: 1
contactPoints:
    # - orgId: 1
    #   name: email receiver
    #   receivers:
    #     - uid: fdh6wc6uviqyob
    #       type: email
    #       settings:
    #         addresses: <example@email.com>
    #       disableResolveMessage: false
    - orgId: 1
      name: hioikawa-Slack
      receivers:
        - uid: cdh6r87abdeypb
          type: slack
          settings:
            mentionGroups: uminomae
            url: https://hooks.slack.com/services/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
            username: hioikawa-Grafana-Alert
          disableResolveMessage: false
    - orgId: 1
      name: hioikawa-Discord
      receivers:
        - uid: ddh6wc6uviqypb
          type: discord
          settings:
            url: https://discord.com/api/webhooks/1223496487917584404/tVeUHpZRrW420zHkvnLcXB5R0OuQ_QY3v44jIkEZk5IkpAFYA42T32h3AVdjQCklS64B
            use_discord_username: true
          disableResolveMessage: false
