version: "3.7"
# docker/srcs/compose-yaml/compose-monitor.yaml
services:
  filebeat:
    container_name: filebeat
    build: 
      context: ./filebeat
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION:?}
    image: filebeat
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ${VOLUME_PATH:?}/log_vol:/var/log/nginx:ro
      - ./filebeat/filebeat-entrypoint.sh:/usr/local/bin/entrypoint.sh
    env_file:
      - .env
    depends_on:
      - nginx
    networks:
      - web_transcendence
      - monitor_transcendence
      - elk
    profiles:
      - monitor

  prometheus:
    container_name: prometheus
    build: ./prometheus
    image: prometheus
    env_file:
      - .env
    ports:
      - "${PROMETHEUS_PORT:?}:9090"
    networks:
      - web_transcendence
      - db_transcendence
      - monitor_transcendence
      - elk
    volumes:
      - ${VOLUME_PATH:?}/prometheus:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    profiles:
      - monitor

  grafana:
    container_name: grafana
    build: ./grafana
    image: grafana
    restart: unless-stopped
    ports:
      - "${GRAFANA_PORT:?}:3000"
    volumes:
      - ${VOLUME_PATH:?}/grafana/:/var/lib/grafana
      # 上記/var/lib/grafanaの中でもdashboradの設定ファイルは、別枠でコンテナイメージに入れたい。方法がわからないのでマウントで対応
      - ./grafana-dev/dashboards/1860-node-exporter-full.json:/var/lib/grafana/dashboards/1860-node-exporter-full.json
    env_file:
      - .env
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel
      - GF_LOG_LEVEL=debug
      # TODO:自己証明書を無視する。本番環境で削除する。
      - GF_PLUGIN_GRAFANA_IMAGE_RENDERER_RENDERING_IGNORE_HTTPS_ERRORS=true
    networks:
      - web_transcendence
      - monitor_transcendence
    profiles:
      - monitor

  grafana-dev:
    container_name: grafana-dev
    build: ./grafana-dev
    image: grafana-dev
    restart: unless-stopped
    ports:
      - "3309:3000"
    volumes:
      - ${VOLUME_PATH:?}/grafana-dev/:/var/lib/grafana
      # 上記/var/lib/grafanaの中でもdashboradの設定ファイルは、別枠でコンテナイメージに入れたい。方法がわからないのでマウントで対応
      - ./grafana-dev/dashboards/1860-node-exporter-full.json:/var/lib/grafana/dashboards/1860-node-exporter-full.json
    env_file:
      - .env
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel
      - GF_LOG_LEVEL=debug
      # TODO:自己証明書を無視する。本番環境で削除する。
      - GF_PLUGIN_GRAFANA_IMAGE_RENDERER_RENDERING_IGNORE_HTTPS_ERRORS=true
    networks:
      - web_transcendence
      - monitor_transcendence
    profiles:
      - monitor
