version: "3.7"
# docker/srcs/compose-yaml/compose-networks.yaml

networks:
  web_transcendence:
    driver: bridge
    name: web_transcendence

  db_transcendence:
    driver: bridge
    name: db_transcendence
    ipam:
      config:
        - subnet: '${DB_NETWORK_SUBNET:?}'
  # blockchain_transcendence:
  #   driver: bridge
  #   name: blockchain_transcendence
  # elastic_transcendence:
  #   driver: bridge
  #   name: elastic_transcendence
  # monitor_transcendence:
  #   driver: bridge
  #   name: monitor_transcendence
  # elk:
  #   # external: true
  #   driver: bridge
  #   name: elk
