# 参考:【Grafana のプロビジョニング | Grafana のドキュメント】 <https://grafana.com/docs/grafana/latest/administration/provisioning/#data-sources>
# 参考:【Prometheus data source | Grafana documentation】 <https://grafana.com/docs/grafana/latest/datasources/prometheus/>

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # <int> Sets the organization id. Defaults to orgId 1.
    orgId: 1
    # <string> Sets a custom UID to reference this data source in other parts of the configuration.
    # If not specified, Grafana generates one.
    # アラートルールに使用する
    uid: ft_trans_prometheus
    # <string> Sets the data source's URL, including the port.
    url: http://prometheus:9090
    # <bool> Toggles whether the data source is pre-selected
    # for new panels. You can set only one default
    # data source per organization.
    isDefault: true
    # <int> Sets the version. Used to compare versions when updating. Ignored when creating a new data source.
    version: 1
    # <bool> Allows users to edit data sources from the Grafana UI.
    editable: true
    # jsonData:
        # データの取得方法
    #   httpMethod: POST
        # GrafanaがPrometheusのアラートを扱うかどうかを決定
        # GrafanaがPrometheusのアラートを直接管理できるようにするもので、アラートの一元管理が必要な場合に便利
    #   manageAlerts: true
    #   prometheusType: Prometheus
    #   prometheusVersion: 2.44.0
        # クエリのレスポンスをどの程度キャッシュするか
        # レスポンスキャッシュを活用してパフォーマンスを向上させたい場合に有効
    #   cacheLevel: 'High'
        # レコーディングルールの無効化
    #   disableRecordingRules: false
        # クエリの時間範囲をどのように重ねるか
    #   incrementalQueryOverlapWindow: 10m
        # トレースデータのリンク先を設定
        # トレースIDのリンク設定は、メトリクスとトレースデータ間の迅速なナビゲーションを可能にし、問題解析を効率化
        # Grafanaはトレースデータを直接可視化するために使われ、Prometheusはメトリクスの収集に使われますが、トレースデータへのリンクを提供することで、メトリクスとトレース間の関連付けを容易に。
    #   exemplarTraceIdDestinations:
    #     # Field with internal link pointing to data source in Grafana.
    #     # datasourceUid value can be anything, but it should be unique across all defined data source uids.
    #     - datasourceUid: my_jaeger_uid
    #       name: traceID

    #     # Field with external link.
    #     - name: traceID
    #       url: 'http://localhost:3000/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Jaeger%22,%7B%22query%22:%22$${__value.raw}%22%7D%5D'