# docker/srcs/prometheus/prometheus.yml
global:
  scrape_interval: 15s 

scrape_configs:
  - job_name: 'nginx'
    scheme: 'http'
    static_configs:
      - targets: ['nginx_exporter:9113']
  - job_name: 'django'
    metrics_path: '/metrics'
    scheme: 'https'
    static_configs:
      - targets: ['nginx:443']
    tls_config:
      insecure_skip_verify: true

# docker exec uwsgi-django sh -c 'curl http://localhost:8000/metrics'
