# docker/srcs/prometheus/prometheus.yml
global:
  scrape_interval: 15s # デフォルトのスクレイプ間隔

scrape_configs:
  - job_name: 'nginx'
    scheme: 'http'
    static_configs:
      - targets: ['nginx_exporter:9113'] # Nginxエクスポーターのアドレスとポート
