version: "3.7"
# docker/srcs/docker-compose-prometheus.yml
services:
  filebeat:
    container_name: filebeat
    build: 
      context: ./filebeat
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    image: filebeat
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ${VOLUME_PATH}/log_vol:/var/log/nginx:ro
      - ./filebeat/filebeat-entrypoint.sh:/usr/local/bin/entrypoint.sh
    env_file:
      - .env
    depends_on:
      - nginx
    networks:
      - web_transcendence
      - monitor_transcendence
      - elk
    # profiles:
    #   - monitor

  prometheus:
    container_name: prometheus
    build: ./prometheus
    image: prometheus
    env_file:
      - .env
    ports:
      - "${PROMETHEUS_PORT}:9090"
    networks:
      - web_transcendence
      - db_transcendence
      - monitor_transcendence
      - elk
    volumes:
      - ${VOLUME_PATH}/prometheus:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    profiles:
      - monitor

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    # restart: unless-stopped
    ports:
     - "${GRAFANA_PORT}:3000"
    volumes:
      - ${VOLUME_PATH}/grafana:/var/lib/grafana
    env_file:
      - .env
    environment:
     - GF_SERVER_ROOT_URL=http://my.grafana.server/
     - GF_INSTALL_PLUGINS=grafana-clock-panel
     - GF_LOG_LEVEL=debug
    networks:
      - web_transcendence
      - monitor_transcendence
    profiles:
      - monitor

  kind-cluster:
    container_name: kind-cluster
    build: ./kind
    image: kind-cluster
    tty: true
    privileged: true
    volumes:
      # - ${VOLUME_PATH}/kind:/var/lib/docker
      # ホストのDockerを制御するため
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kind/kind-config.yaml:/kind-config.yaml
      - ./kind/entrypoint.sh:/usr/local/bin/entrypoint.sh
      - ./kind/host_ip.sh:/host_ip.sh
    command: >
      sh -c "
      tail -f /dev/null
      "
    networks:
      - monitor_transcendence
    # network_mode: "host"
    ports:
      - "10443:10443"
      - "10444:9090"
    # profiles:
    #   - monitor
