version: "3.7"
# docker/srcs/docker-compose-web.yml
services:
  hardhat:
    container_name: hardhat
    build: ./hardhat
    image: hardhat
    env_file:
      - .env
    ports:
      - ${HARDHAT_PORT}:8545
    volumes:
    # - ${VOLUME_PATH}/hardhat/artifacts:/app/artifacts
    - ./hardhat/hardhat_pj/artifacts:/app/artifacts
    - ./hardhat/hardhat_pj/contracts:/app/contracts
    - ./hardhat/hardhat_pj/scripts:/app/scripts
    - ./hardhat/hardhat_pj/test:/app/test
    - ./hardhat/hardhat_pj/share:/app/share
    - ./hardhat/hardhat_pj/hardhat.config.ts:/app/hardhat.config.ts
    networks:
      - blockchain_transcendence
    profiles:
      - blockchain
  ganache:
    container_name: ganache
    build: ./ganache
    image: ganache
    env_file:
      - .env
    ports:
       - "8555:8545"
    stdin_open: true
    tty: true
    networks:
      - blockchain_transcendence
    profiles:
      - blockchain