version: "3.7"
# docker/srcs/docker-compose-web.yml
services:
  hardhat:
    container_name: hardhat
    build: ./hardhat
    image: hardhat
    env_file:
      - .env
    ports:
      - ${HARDHAT_PORT}:8545
    volumes:
    # # コンパイルされたアーティファクトを保管するディレクトリ
    # - ${VOLUME_PATH}/hardhat/artifacts:/app/artifacts
    # - ${VOLUME_PATH}/hardhat/test-results:/app/test-results
    - ./hardhat/hardhat_pj/artifacts:/app/artifacts
    - ./hardhat/hardhat_pj/contracts:/app/contracts
    - ./hardhat/hardhat_pj/scripts:/app/scripts
    - ./hardhat/hardhat_pj/test-results:/app/test-results
    - ./hardhat/hardhat_pj/test:/app/test
    networks:
      - blockchain_transcendence
    