version: "3.7"
# docker/srcs/docker-compose-yml/docker-compose-exporter.yml

services:
  nginx_exporter:
    container_name: nginx_exporter
    image: nginx/nginx-prometheus-exporter
    ports:
      - "9113:9113"
    command: ["-nginx.scrape-uri=http://localhost:${NGINX_PORT}/stub_status"]
    networks:
      - monitor_transcendence
    volumes:
      - ${VOLUME_PATH}/exporters:/exporters
    profiles:
      - monitor

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:v1.0.1
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points'
      - '^/(sys|proc|dev|host|etc)($|/)'
    ports:
      - 9100:9100
    networks:
      - monitor_transcendence
    profiles:
      - monitor

  cadvisor:
    container_name: cadvisor
    image: gcr.io/google-containers/cadvisor:v0.36.0
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    networks:
      - monitor_transcendence
    profiles:
      - monitor
  
  elasticsearch-exporter:
    container_name: elasticsearch-exporter
    image: quay.io/prometheuscommunity/elasticsearch-exporter:latest
    command:
     - '--es.uri=http://elasticsearch:9200'
    restart: always
    networks:
      - monitor_transcendence
    ports:
    - "9114:9114"